FROM php:8.3-fpm
RUN apt-get update && apt-get install -y git unzip libpq-dev curl && docker-php-ext-install pdo pdo_pgsql
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
WORKDIR /var/www/html

