services:
  app:
    build: ./docker/php
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    env_file: ./docker/app.env
    depends_on:
      db:
        condition: service_healthy
  web:
    image: nginx:1.27-alpine
    ports: ["8080:80"]
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      app:
        condition: service_started
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
    volumes: [db-data:/var/lib/postgresql/data]
volumes:
  db-data:
