name: Contract Check

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  schemathesis:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare env files for Docker
        run: |
          # docker/app.env はGit管理外。CIではexampleから生成
          if [ ! -f docker/app.env ]; then cp docker/app.env.example docker/app.env; fi

      - name: Show Docker info
        run: |
          docker --version
          docker compose version

      - name: Build and start services (wait if supported)
        run: docker compose up -d --build

      - name: Install PHP dependencies (Composer)
        run: |
          docker compose exec -T app composer install --no-interaction --prefer-dist --no-ansi --no-progress

      - name: Prepare .env and APP_KEY
        run: |
          if [ ! -f src/.env ]; then cp src/.env.example src/.env; fi
          docker compose exec -T app php artisan key:generate

      - name: Run migrations
        run: |
          docker compose exec -T app php artisan migrate --force

      - name: Wait for web (HTTP 200)
        run: |
          curl --fail --silent --show-error \
               --retry 60 --retry-all-errors --retry-delay 2 \
               --connect-timeout 2 --max-time 180 \
               http://localhost:8080/ > /dev/null

      - name: Run contract tests (Schemathesis)
        run: |
          make contract-check

      - name: Teardown
        if: always()
        run: |
          docker compose logs --no-color > docker-logs.txt || true
          docker compose down -v
