name: Contract Check

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  schemathesis:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare env files for Docker
        run: |
          # docker/app.env はGit管理外。CIではexampleから生成
          if [ ! -f docker/app.env ]; then cp docker/app.env.example docker/app.env; fi

      - name: Show Docker info
        run: |
          docker --version
          docker compose version

      - name: Build and start services (wait if supported)
        run: docker compose up -d --build

      - name: Install PHP dependencies (Composer)
        run: |
          docker compose exec -T app composer install --no-interaction --prefer-dist --no-ansi --no-progress

      - name: Fix permissions for storage and cache
        run: |
          docker compose exec -T app sh -lc '
            mkdir -p /var/www/html/storage /var/www/html/bootstrap/cache && \
            chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && \
            chmod -R ug+rwX /var/www/html/storage /var/www/html/bootstrap/cache
          '

      - name: Prepare .env and APP_KEY
        run: |
          if [ ! -f src/.env ]; then cp src/.env.example src/.env; fi
          docker compose exec -T app php artisan key:generate

      - name: Clear Laravel caches
        run: |
          docker compose exec -T app php artisan config:clear || true
          docker compose exec -T app php artisan view:clear || true
          docker compose exec -T app php artisan route:clear || true

      - name: Run migrations
        run: |
          docker compose exec -T app php artisan migrate --force

      - name: Wait for web (HTTP 200)
        run: |
          curl --fail --silent --show-error \
               --retry 20 --retry-all-errors --retry-delay 2 \
               --connect-timeout 2 --max-time 180 \
               http://localhost:8080/ > /dev/null

      - name: Run contract tests (Schemathesis)
        run: |
          make contract-check

      - name: Collect diagnostics
        if: always()
        run: |
          mkdir -p artifacts
          docker compose ps > artifacts/compose-ps.txt || true
          docker compose logs --no-color > artifacts/compose-logs.txt || true
          docker compose logs web > artifacts/web.log || true
          docker compose logs app > artifacts/app.log || true
          docker compose logs db > artifacts/db.log || true
          # HTTP レスポンスのヘッダ/本文を保存
          curl -sS -D artifacts/http-headers.txt -o artifacts/http-body.html http://localhost:8080/ || true
          # Laravel アプリ内のログを収集
          docker compose exec -T app sh -lc 'ls -lah storage/logs || true' > artifacts/laravel-logs-ls.txt || true
          docker compose exec -T app sh -lc 'for f in storage/logs/*.log 2>/dev/null; do echo "===== $f ====="; tail -n 500 "$f"; echo; done' > artifacts/laravel-logs-tail.txt || true

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: diagnostics
          path: artifacts

      - name: Teardown
        if: always()
        run: |
          docker compose down -v
